# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Statistics-Lmoments
version:      0.03
version_from: Lmoments.pm
installdirs:  site
requires:
    ExtUtils::F77:                 0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.21
